### ISSUE TITLE
loctree2-data unavailable

### ISSUE THREAD

**Issue by MatDal** [Rostlab/LocTree#8] opened 2017-07-27 17:49 UTC
Hello,
An error appeared when i used loctree3:

Resolving rostlab.org (rostlab.org)... 131.159.28.73
Connecting to rostlab.org (rostlab.org)|131.159.28.73|:21... failed: Connection refused.
loctree2 package data is missing from /usr/share/loctree2-data and automatic retrieval failed. Please download it from ftp://rostlab.org/free/loctree2-data-1.0.2.tar.gz and untar it to /usr/share/loctree2-data.
Since the download is restartable, you also can re-run this command '/home/manager/LocTree3/install/share/loctree3/loctree2data' to reattempt data download. The incomplete data file is in /tmp/loctree2-data-1.0.2.tar.gz.

but the link is unavailable
ftp://rostlab.org/free/loctree2-data-1.0.2.tar.gz

Thanks
Best Regards

**Comment by BernhoferM** [comment] 2017-07-27 18:42
Dear MatDal,

it appears that our ftp-server is currently not working as intended. I've forwarded the issue to our system administrator.

Regards
Michael

**Comment by MatDal** [comment] 2017-07-28 10:01
Ok,
Thanks a lot,
and very nice tool, good work.

Best,
Mattia

**Comment by BernhoferM** [comment] 2017-07-31 08:40
Hi,
the ftp server should be working again.

Regards
Michael

**Comment by juanmirocks** [comment] 2017-07-31 10:38
Closing as it is likely resolved now

@MatDal please reopen this if you have further problems

**Closed as completed by juanmirocks** 2017-07-31 10:38 UTC
